name: midas-gin-cpu-cs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.16.4=pyhd8ed1ab_0
  - binutils=2.44=h4852527_1
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - binutils_linux-64=2.44=h4852527_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-compiler=1.11.0=h4d9bdce_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cmake=4.1.0=hc85cc9f_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.9.0=pyh707e725_1
  - compilers=1.11.0=ha770c72_0
  - conda-gcc-specs=14.3.0=hb991d5c_4
  - cxx-compiler=1.11.0=hfcd1e18_0
  - fortran-compiler=1.11.0=h9bea470_0
  - gcc=14.3.0=h76bdaa0_4
  - gcc_impl_linux-64=14.3.0=hd9e9e21_4
  - gcc_linux-64=14.3.0=h1382650_11
  - gfortran=14.3.0=he448592_4
  - gfortran_impl_linux-64=14.3.0=h7db7018_4
  - gfortran_linux-64=14.3.0=h30a37f7_11
  - git=2.49.0=pl5321hc2ff736_2
  - greenlet=3.2.4=py39h818bca1_0
  - gxx=14.3.0=he448592_4
  - gxx_impl_linux-64=14.3.0=he663afc_4
  - gxx_linux-64=14.3.0=ha7acb78_11
  - imbalanced-learn=0.12.4=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.9.0=34_h59b9bed_openblas
  - libcblas=3.9.0=34_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-devel_linux-64=14.3.0=h85bb3a7_104
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran-ng=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=34_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libsanitizer=14.3.0=hd08acf3_4
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-devel_linux-64=14.3.0=h85bb3a7_104
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.8=h4922eb0_2
  - make=4.4.1=hb9d3cd8_2
  - mako=1.3.10=pyhd8ed1ab_0
  - markupsafe=3.0.2=py39h9399b63_1
  - ncurses=6.5=h2d0b736_3
  - numpy=1.26.4=py39h474f0d3_0
  - openssl=3.5.2=h26f9b46_0
  - optuna=4.4.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h1b6b32d_0
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.2=pyh8b19718_0
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - readline=8.2=h8c095d6_2
  - rhash=1.4.6=hb9d3cd8_1
  - scikit-learn=1.4.2=py39h40c85ba_1
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.43=py39hd399759_0
  - sqlite=3.50.4=hbc0de68_0
  - sysroot_linux-64=2.17=h0157908_18
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.2.1=pyhe01879c_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - idna==3.10
      - jinja2==3.1.4
      - mpmath==1.3.0
      - multidict==6.6.4
      - networkx==3.2.1
      - pillow==11.0.0
      - propcache==0.3.2
      - psutil==7.0.0
      - pyparsing==3.2.3
      - requests==2.32.5
      - sympy==1.13.1
      - urllib3==2.5.0
      - yarl==1.20.1