
name: midas-gin-gpu
channels:
  - conda-forge
dependencies:
  # Core
  - python=3.9
  - pip
  - numpy=1.26
  - pandas=2.3
  - scikit-learn=1.4       # scikit-learn 1.2.2 in windows
  - imbalanced-learn=0.12
  - optuna=4.4             # optuna 3.0.3 in windows
  - joblib
  - tqdm
  - pytz
  - python-dateutil
  - sqlalchemy            # Optuna's sqlite backend - 1.4.44 in windows
  - sqlite                # CLI / libraries for sqlite storage

  # Build toolchain (needed to compile xswap)
  - compilers             # meta-package: C/C++ toolchain
  - cmake
  - make
  - git
  - llvm-openmp
  - wheel
  - setuptools